name: php-database
recipe: lamp
#env_file:
#  - .env
config:
  php: '7.3'
  webroot: public/
  xdebug: true
#  config:
#    php: php.ini
proxy:
  appserver:
    - php-database.lndo.site
services:
  appserver:
    build:
      - composer install
#  node:
#    type: node
#    build:
#      - npm install
#      - npm run build
#tooling:
#  npm:
#    description: Builds the frontend
#    service: node